apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/skknox/got-spring-boot-app:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/skknox/got-spring-boot-app:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: got-spring-boot-app
        chartPath: charts/got-spring-boot-app
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/skknox/got-spring-boot-app'
          image.tag: '{{.DIGEST_HEX}}'
